

CREATE DATABASE LiderCloset
GO
USE LiderCloset
GO 


ALTER LOGIN sa WITH PASSWORD = 'baotran0911';

CREATE TABLE tblHANGMUC (
	MaHangMuc INT PRIMARY KEY IDENTITY(1,1), 
	TenHangMuc NVARCHAR(70) NOT NULL, 
	HM_ImageUrl NVARCHAR(MAX) NOT NULL, 
	isActive BIT NULL, 
	NgayCapNhat DATETIME NULL,
);
CREATE TABLE tblHANGMUCCON (
	MaHMC INT PRIMARY KEY IDENTITY(1,1),
	TenHMC NVARCHAR(100),
	MaHangMuc INT FOREIGN KEY REFERENCES tblHANGMUC(MaHangMuc) ON DELETE CASCADE NOT NULL,
	isActive BIT, 
	NgayCapNhat DATETIME,
);


select * from tbluser 

CREATE TABLE tblSANPHAM (
	MaSP INT PRIMARY KEY IDENTITY(1,1), 
	TenSP NVARCHAR(70) NULL,
	MoTaNgan NVARCHAR(200) NULL,
	MoTaDai NVARCHAR(MAX) NULL, 
	MoTaBoSung NVARCHAR(MAX) NULL,
	DonGia DECIMAL(18,2) NULL, 
	SoLuong INT NULL, 
	Size NVARCHAR(30) NULL,
	MauSac NVARCHAR(30) NULL,
	TenNCC NVARCHAR(100) NULL,
	MaHangMuc INT FOREIGN KEY REFERENCES tblHANGMUC(MaHangMuc) ON DELETE CASCADE NOT NULL,
	MaHMC INT NOT NULL,
	isActive BIT NULL, 
	isCustomized BIT NULL,
	DaBan INT NULL,
	NgayCapNhat DATETIME NOT NULL,
);
CREATE TABLE ProductImages (
	MaHinh INT PRIMARY KEY IDENTITY(1,1),
	ImageUrl VARCHAR(MAX) NULL,
	MaSP INT FOREIGN KEY REFERENCES tblSANPHAM(MaSP) ON DELETE CASCADE NOT NULL,
	AnhHH BIT NULL, 
);
CREATE TABLE tblCHUCVU (
	MaCV INT PRIMARY KEY,
	TenCV NVARCHAR(50) NOT NULL,
)
INSERT INTO tblCHUCVU VALUES (1, 'Admin'),
INSERT INTO tblCHUCVU VALUES (2, 'Khách hàng');

CREATE TABLE tblUSER (
	UserID INT PRIMARY KEY IDENTITY(1,1),
	TenUser NVARCHAR(70) NULL UNIQUE,
	UserName NVARCHAR(70) NULL,
	Mobile NVARCHAR(50) NULL,
	Email NVARCHAR(70) NULL UNIQUE,
	DiaChiUser NVARCHAR(MAX) NULL, 
	PostCode NVARCHAR(50) NULL, 
	PassWord NVARCHAR(70) NULL,
	ImageURL NVARCHAR(MAX) NULL,
	MaCV INT FOREIGN KEY REFERENCES tblCHUCVU(MaCV) ON DELETE CASCADE NOT NULL,
	NgayTaoUS DATETIME NOT NULL,
);
CREATE TABLE tblREVIEWSP (
	MaRV INT PRIMARY KEY IDENTITY(1,1),
	Sao INT NOT NULL,
	BinhLuan NVARCHAR(MAX) NULL,
	MaSP INT FOREIGN KEY REFERENCES tblSANPHAM(MaSP) ON DELETE CASCADE NOT NULL,
	UserID INTEGER FOREIGN KEY REFERENCES tblUSER(UserID) ON DELETE CASCADE NOT NULL,
	NgayTaoRV DATETIME NOT NULL,

);
CREATE TABLE tblDSYEUTHICH (
	MaDSYT INT PRIMARY KEY IDENTITY(1,1),
	MaSP INT FOREIGN KEY REFERENCES tblSANPHAM(MaSP) ON DELETE CASCADE NOT NULL,
	UserID INTEGER FOREIGN KEY REFERENCES tblUSER(UserID) ON DELETE CASCADE NOT NULL,
	NgayTaoDSYT DATETIME NOT NULL,
);

CREATE TABLE tblGIOHANG (
	MaGioHang INT PRIMARY KEY IDENTITY(1,1), 
	MaSP INT,
	SoLuong INT NOT NULL,
	UserID INTEGER NOT NULL,
	NgayTaoGioHang DATETIME NOT NULL,
);
CREATE TABLE tblLIENHE (
	MaLH INT PRIMARY KEY IDENTITY(1,1),
	TenLH NVARCHAR(50) NULL,
	EmailLH	NVARCHAR(50) NULL,
	TieuDe NVARCHAR(200) NULL,
	LoiNhan NVARCHAR(MAX) NULL,
	NgayTaoLH DATETIME NOT NULL,
);
CREATE TABLE tblTHANHTOAN (
	MaTT INT PRIMARY KEY IDENTITY(1,1),
	TenTT NVARCHAR(50) NULL,
	SoThe NVARCHAR(50) NULL,
	NgayDaoHan DATETIME NULL,
	DiaChi NVARCHAR(MAX) NULL,
	SoCVV CHAR(20) NULL,
	TinhTrangTT NVARCHAR(50)
);

CREATE TABLE tblDONHANG (
	MaDH INT PRIMARY KEY IDENTITY(1,1),
	STT_DH NVARCHAR(MAX) NULL,
	MaSP INT FOREIGN KEY REFERENCES tblSANPHAM(MaSP) ON DELETE CASCADE NOT NULL,
	SoLuong INT NULL,
	UserID INTEGER FOREIGN KEY REFERENCES tblUSER(UserID) ON DELETE CASCADE NOT NULL,
	TinhTrangDH NVARCHAR(50) NULL,
	MaTT INT FOREIGN KEY REFERENCES tblTHANHTOAN(MaTT) ON DELETE CASCADE NOT NULL,
	NgayTaoDH DATETIME NOT NULL,
	IsCancel BIT NOT NULL DEFAULT 0
);

-- Tạo bảng tblCOUPON
CREATE TABLE tblCOUPON
(
    CouponCode NVARCHAR(50) PRIMARY KEY,
    DiscountPercent DECIMAL(5,2),
    IsActive BIT DEFAULT 1,
    ExpiryDate DATETIME
);

-- Dữ liệu mẫu cho tblCOUPON
INSERT INTO tblCOUPON (CouponCode, DiscountPercent, IsActive, ExpiryDate)
VALUES 
    ('SAVE10', 10, 1, '2025-12-31'),
    ('SAVE20', 20, 1, '2025-12-31'),
    ('EXPIRED', 15, 0, '2025-04-01');

-- Tạo bảng tblCHITIETDONHANG
CREATE TABLE tblCHITIETDONHANG
(
    MaDH INT,
    MaSP INT,
    Size NVARCHAR(30),
    MauSac NVARCHAR(30),
    SoLuong INT,
    Gia DECIMAL(18,2),
    PRIMARY KEY (MaDH, MaSP, Size, MauSac),
    FOREIGN KEY (MaDH) REFERENCES tblDONHANG(MaDH),
    FOREIGN KEY (MaSP) REFERENCES tblSANPHAM(MaSP)
);

-- Sửa bảng tblGIOHANG để thêm Size và MauSac
ALTER TABLE tblGIOHANG
ADD Size NVARCHAR(30) NULL,
    MauSac NVARCHAR(30) NULL;


	ALTER TABLE tblGIOHANG
ADD CONSTRAINT FK_GioHang_SanPham FOREIGN KEY (MaSP) REFERENCES tblSANPHAM(MaSP) ON DELETE CASCADE,
    CONSTRAINT FK_GioHang_User FOREIGN KEY (UserID) REFERENCES tblUSER(UserID) ON DELETE CASCADE;


ALTER TABLE tblDONHANG
ADD TongTien DECIMAL(18,2) NULL;


INSERT INTO tblTHANHTOAN (TenTT, TinhTrangTT)
VALUES ('Thanh toán khi nhận hàng', 'Active'),
       ('Thẻ tín dụng', 'Active');


	   INSERT INTO tblHANGMUC (TenHangMuc, HM_ImageUrl, isActive, NgayCapNhat)
VALUES ('Áo', '/Images/ao.jpg', 1, GETDATE()),
       ('Quần', '/Images/quan.jpg', 1, GETDATE());

INSERT INTO tblHANGMUCCON (TenHMC, MaHangMuc, isActive, NgayCapNhat)
VALUES ('Áo thun', 1, 1, GETDATE()),
       ('Quần jeans', 2, 1, GETDATE());


	   select * from tbluser 